export const WATCH_CONFIG_STORAGE_KEY = "watch-config";

export const TIMEZONE_OPTIONS = [
  { label: "Afghanistan", timezone: "Asia/Kabul" },
  { label: "Albania", timezone: "Europe/Tirane" },
  { label: "Algeria", timezone: "Africa/Algiers" },
  { label: "Andorra", timezone: "Europe/Andorra" },
  { label: "Angola", timezone: "Africa/Luanda" },
  { label: "Antigua and Barbuda", timezone: "America/Antigua" },
  { label: "Argentina", timezone: "America/Argentina/Buenos_Aires" },
  { label: "Armenia", timezone: "Asia/Yerevan" },
  { label: "Australia", timezone: "Australia/Sydney" },
  { label: "Austria", timezone: "Europe/Vienna" },
  { label: "Azerbaijan", timezone: "Asia/Baku" },
  { label: "Bahamas", timezone: "America/Nassau" },
  { label: "Bahrain", timezone: "Asia/Bahrain" },
  { label: "Bangladesh", timezone: "Asia/Dhaka" },
  { label: "Barbados", timezone: "America/Barbados" },
  { label: "Belarus", timezone: "Europe/Minsk" },
  { label: "Belgium", timezone: "Europe/Brussels" },
  { label: "Belize", timezone: "America/Belize" },
  { label: "Benin", timezone: "Africa/Porto-Novo" },
  { label: "Bhutan", timezone: "Asia/Thimphu" },
  { label: "Bolivia (Plurinational State of)", timezone: "America/La_Paz" },
  { label: "Bosnia and Herzegovina", timezone: "Europe/Sarajevo" },
  { label: "Botswana", timezone: "Africa/Gaborone" },
  { label: "Brazil", timezone: "America/Sao_Paulo" },
  { label: "Brunei Darussalam", timezone: "Asia/Brunei" },
  { label: "Bulgaria", timezone: "Europe/Sofia" },
  { label: "Burkina Faso", timezone: "Africa/Ouagadougou" },
  { label: "Burundi", timezone: "Africa/Bujumbura" },
  { label: "Cabo Verde", timezone: "Atlantic/Cape_Verde" },
  { label: "Cambodia", timezone: "Asia/Phnom_Penh" },
  { label: "Cameroon", timezone: "Africa/Douala" },
  { label: "Canada", timezone: "America/Toronto" },
  { label: "Central African Republic", timezone: "Africa/Bangui" },
  { label: "Chad", timezone: "Africa/Ndjamena" },
  { label: "Chile", timezone: "America/Santiago" },
  { label: "China", timezone: "Asia/Shanghai" },
  { label: "Colombia", timezone: "America/Bogota" },
  { label: "Comoros", timezone: "Indian/Comoro" },
  { label: "Congo", timezone: "Africa/Brazzaville" },
  { label: "Cook Islands", timezone: "Pacific/Rarotonga" },
  { label: "Costa Rica", timezone: "America/Costa_Rica" },
  { label: "Côte d'Ivoire", timezone: "Africa/Abidjan" },
  { label: "Croatia", timezone: "Europe/Zagreb" },
  { label: "Cuba", timezone: "America/Havana" },
  { label: "Cyprus", timezone: "Asia/Nicosia" },
  { label: "Czechia", timezone: "Europe/Prague" },
  { label: "Democratic People's Republic of Korea", timezone: "Asia/Pyongyang" },
  { label: "Democratic Republic of the Congo", timezone: "Africa/Kinshasa" },
  { label: "Denmark", timezone: "Europe/Copenhagen" },
  { label: "Djibouti", timezone: "Africa/Djibouti" },
  { label: "Dominica", timezone: "America/Dominica" },
  { label: "Dominican Republic", timezone: "America/Santo_Domingo" },
  { label: "Ecuador", timezone: "America/Guayaquil" },
  { label: "Egypt", timezone: "Africa/Cairo" },
  { label: "El Salvador", timezone: "America/El_Salvador" },
  { label: "Equatorial Guinea", timezone: "Africa/Malabo" },
  { label: "Eritrea", timezone: "Africa/Asmara" },
  { label: "Estonia", timezone: "Europe/Tallinn" },
  { label: "Eswatini", timezone: "Africa/Mbabane" },
  { label: "Ethiopia", timezone: "Africa/Addis_Ababa" },
  { label: "Fiji", timezone: "Pacific/Fiji" },
  { label: "Finland", timezone: "Europe/Helsinki" },
  { label: "France", timezone: "Europe/Paris" },
  { label: "Gabon", timezone: "Africa/Libreville" },
  { label: "Gambia", timezone: "Africa/Banjul" },
  { label: "Georgia", timezone: "Asia/Tbilisi" },
  { label: "Germany", timezone: "Europe/Berlin" },
  { label: "Ghana", timezone: "Africa/Accra" },
  { label: "Greece", timezone: "Europe/Athens" },
  { label: "Grenada", timezone: "America/Grenada" },
  { label: "Guatemala", timezone: "America/Guatemala" },
  { label: "Guinea", timezone: "Africa/Conakry" },
  { label: "Guinea-Bissau", timezone: "Africa/Bissau" },
  { label: "Guyana", timezone: "America/Guyana" },
  { label: "Haiti", timezone: "America/Port-au-Prince" },
  { label: "Honduras", timezone: "America/Tegucigalpa" },
  { label: "Hungary", timezone: "Europe/Budapest" },
  { label: "Iceland", timezone: "Atlantic/Reykjavik" },
  { label: "India", timezone: "Asia/Kolkata" },
  { label: "Indonesia", timezone: "Asia/Jakarta" },
  { label: "Iran (Islamic Republic of)", timezone: "Asia/Tehran" },
  { label: "Iraq", timezone: "Asia/Baghdad" },
  { label: "Ireland", timezone: "Europe/Dublin" },
  { label: "Israel", timezone: "Asia/Jerusalem" },
  { label: "Italy", timezone: "Europe/Rome" },
  { label: "Jamaica", timezone: "America/Jamaica" },
  { label: "Japan", timezone: "Asia/Tokyo" },
  { label: "Jordan", timezone: "Asia/Amman" },
  { label: "Kazakhstan", timezone: "Asia/Almaty" },
  { label: "Kenya", timezone: "Africa/Nairobi" },
  { label: "Kiribati", timezone: "Pacific/Tarawa" },
  { label: "Kuwait", timezone: "Asia/Kuwait" },
  { label: "Kyrgyzstan", timezone: "Asia/Bishkek" },
  { label: "Lao People's Democratic Republic", timezone: "Asia/Vientiane" },
  { label: "Latvia", timezone: "Europe/Riga" },
  { label: "Lebanon", timezone: "Asia/Beirut" },
  { label: "Lesotho", timezone: "Africa/Maseru" },
  { label: "Liberia", timezone: "Africa/Monrovia" },
  { label: "Libya", timezone: "Africa/Tripoli" },
  { label: "Lithuania", timezone: "Europe/Vilnius" },
  { label: "Luxembourg", timezone: "Europe/Luxembourg" },
  { label: "Madagascar", timezone: "Indian/Antananarivo" },
  { label: "Malawi", timezone: "Africa/Blantyre" },
  { label: "Malaysia", timezone: "Asia/Kuala_Lumpur" },
  { label: "Maldives", timezone: "Indian/Maldives" },
  { label: "Mali", timezone: "Africa/Bamako" },
  { label: "Malta", timezone: "Europe/Malta" },
  { label: "Marshall Islands", timezone: "Pacific/Majuro" },
  { label: "Mauritania", timezone: "Africa/Nouakchott" },
  { label: "Mauritius", timezone: "Indian/Mauritius" },
  { label: "Mexico", timezone: "America/Mexico_City" },
  { label: "Micronesia (Federated States of)", timezone: "Pacific/Chuuk" },
  { label: "Monaco", timezone: "Europe/Monaco" },
  { label: "Mongolia", timezone: "Asia/Ulaanbaatar" },
  { label: "Montenegro", timezone: "Europe/Podgorica" },
  { label: "Morocco", timezone: "Africa/Casablanca" },
  { label: "Mozambique", timezone: "Africa/Maputo" },
  { label: "Myanmar", timezone: "Asia/Yangon" },
  { label: "Namibia", timezone: "Africa/Windhoek" },
  { label: "Naoero", timezone: "Pacific/Nauru" },
  { label: "Nepal", timezone: "Asia/Kathmandu" },
  { label: "Netherlands", timezone: "Europe/Amsterdam" },
  { label: "New Zealand", timezone: "Pacific/Auckland" },
  { label: "Nicaragua", timezone: "America/Managua" },
  { label: "Niger", timezone: "Africa/Niamey" },
  { label: "Nigeria", timezone: "Africa/Lagos" },
  { label: "Niue", timezone: "Pacific/Niue" },
  { label: "North Macedonia", timezone: "Europe/Skopje" },
  { label: "Norway", timezone: "Europe/Oslo" },
  { label: "Oman", timezone: "Asia/Muscat" },
  { label: "Pakistan", timezone: "Asia/Karachi" },
  { label: "Palau", timezone: "Pacific/Palau" },
  { label: "Panama", timezone: "America/Panama" },
  { label: "Papua New Guinea", timezone: "Pacific/Port_Moresby" },
  { label: "Paraguay", timezone: "America/Asuncion" },
  { label: "Peru", timezone: "America/Lima" },
  { label: "Philippines", timezone: "Asia/Manila" },
  { label: "Poland", timezone: "Europe/Warsaw" },
  { label: "Portugal", timezone: "Europe/Lisbon" },
  { label: "Qatar", timezone: "Asia/Qatar" },
  { label: "Republic of Korea", timezone: "Asia/Seoul" },
  { label: "Republic of Moldova", timezone: "Europe/Chisinau" },
  { label: "Romania", timezone: "Europe/Bucharest" },
  { label: "Russian Federation", timezone: "Europe/Moscow" },
  { label: "Rwanda", timezone: "Africa/Kigali" },
  { label: "Saint Kitts and Nevis", timezone: "America/St_Kitts" },
  { label: "Saint Lucia", timezone: "America/St_Lucia" },
  { label: "Saint Vincent and the Grenadines", timezone: "America/St_Vincent" },
  { label: "Samoa", timezone: "Pacific/Apia" },
  { label: "San Marino", timezone: "Europe/San_Marino" },
  { label: "Sao Tome and Principe", timezone: "Africa/Sao_Tome" },
  { label: "Saudi Arabia", timezone: "Asia/Riyadh" },
  { label: "Senegal", timezone: "Africa/Dakar" },
  { label: "Serbia", timezone: "Europe/Belgrade" },
  { label: "Seychelles", timezone: "Indian/Mahe" },
  { label: "Sierra Leone", timezone: "Africa/Freetown" },
  { label: "Singapore", timezone: "Asia/Singapore" },
  { label: "Slovakia", timezone: "Europe/Bratislava" },
  { label: "Slovenia", timezone: "Europe/Ljubljana" },
  { label: "Solomon Islands", timezone: "Pacific/Guadalcanal" },
  { label: "Somalia", timezone: "Africa/Mogadishu" },
  { label: "South Africa", timezone: "Africa/Johannesburg" },
  { label: "South Sudan", timezone: "Africa/Juba" },
  { label: "Spain", timezone: "Europe/Madrid" },
  { label: "Sri Lanka", timezone: "Asia/Colombo" },
  { label: "Sudan", timezone: "Africa/Khartoum" },
  { label: "Suriname", timezone: "America/Paramaribo" },
  { label: "Sweden", timezone: "Europe/Stockholm" },
  { label: "Switzerland", timezone: "Europe/Zurich" },
  { label: "Syrian Arab Republic", timezone: "Asia/Damascus" },
  { label: "Tajikistan", timezone: "Asia/Dushanbe" },
  { label: "Thailand", timezone: "Asia/Bangkok" },
  { label: "Timor-Leste", timezone: "Asia/Dili" },
  { label: "Togo", timezone: "Africa/Lome" },
  { label: "Tonga", timezone: "Pacific/Tongatapu" },
  { label: "Trinidad and Tobago", timezone: "America/Port_of_Spain" },
  { label: "Tunisia", timezone: "Africa/Tunis" },
  { label: "Türkiye", timezone: "Europe/Istanbul" },
  { label: "Turkmenistan", timezone: "Asia/Ashgabat" },
  { label: "Tuvalu", timezone: "Pacific/Funafuti" },
  { label: "Uganda", timezone: "Africa/Kampala" },
  { label: "Ukraine", timezone: "Europe/Kyiv" },
  { label: "United Arab Emirates", timezone: "Asia/Dubai" },
  { label: "United Kingdom of Great Britain and Northern Ireland", timezone: "Europe/London" },
  { label: "United Republic of Tanzania", timezone: "Africa/Dar_es_Salaam" },
  { label: "United States of America", timezone: "America/New_York" },
  { label: "Uruguay", timezone: "America/Montevideo" },
  { label: "Uzbekistan", timezone: "Asia/Tashkent" },
  { label: "Vanuatu", timezone: "Pacific/Efate" },
  { label: "Venezuela (Bolivarian Republic of)", timezone: "America/Caracas" },
  { label: "Viet Nam", timezone: "Asia/Ho_Chi_Minh" },
  { label: "Yemen", timezone: "Asia/Aden" },
  { label: "Zambia", timezone: "Africa/Lusaka" },
  { label: "Zimbabwe", timezone: "Africa/Harare" }
];

export const WATCH_COUNTRY_OPTIONS = [
  { label: "New York", timezone: "America/New_York", flag: "🇺🇸" },
  { label: "Australia", timezone: "Australia/Sydney", flag: "🇦🇺" },
  { label: "London", timezone: "Europe/London", flag: "🇬🇧" },
  { label: "India", timezone: "Asia/Kolkata", flag: "🇮🇳" },
  { label: "Russia", timezone: "Europe/Moscow", flag: "🇷🇺" },
  { label: "Japan", timezone: "Asia/Tokyo", flag: "🇯🇵" },
  { label: "Dubai", timezone: "Asia/Dubai", flag: "🇦🇪" }
];

export const DEFAULT_WATCH_CONFIG = WATCH_COUNTRY_OPTIONS;
